shell /usr/bin/zsh
# ====== FUENTE ======
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
font_size        14

# ====== APARIENCIA / TRANSPARENCIA ======
# Base negra para que el blur de KDE se vea “glass”
foreground               #d8dee9
background               #0a0a0f
background_opacity       0.50     
enable_background_blur 	 yes 		 1
background_blur 50
linux_display_server x11
dynamic_background_opacity yes

cursor_shape             beam
cursor_blink             yes
window_padding_width     8
hide_window_decorations  no
confirm_os_window_close  0
scrollback_lines         10000
enable_audio_bell        no
tab_bar_style            powerline

# ====== PALETA (oscura, tipo Nord/Black mix) ======
color0  #151820
color8  #2a2f3a
color1  #bf616a
color9  #d06f79
color2  #a3be8c
color10 #b1d196
color3  #ebcb8b
color11 #f0d399
color4  #81a1c1
color12 #88c0d0
color5  #b48ead
color13 #c895bf
color6  #88c0d0
color14 #8fbcbb
color7  #c7ccd7
color15 #e5e9f0
selection_background #2b2f3a
url_color            #88c0d0
cursor               #e6edf3

# ====== ATAJOS ÚTILES (opacidad en vivo) ======
# Sube/baja opacidad (ayuda a ver más o menos blur sin editar el archivo)
map ctrl+alt+equal  set_background_opacity +0.03
map ctrl+alt+minus  set_background_opacity -0.03
map ctrl+alt+0      set_background_opacity 0.84

# Navegación de pestañas
map ctrl+shift+enter  launch --type=tab
map ctrl+shift+left   previous_tab
map ctrl+shift+right  next_tab
map ctrl+shift+w      close_tab
map ctrl+shift+f      toggle_fullscreen

# ====== WAYLAND ======
linux_display_server auto
